CREATE TABLE APPUSERS (
	ID INT IDENTITY(1,1) NOT NULL,
	USERNAME NVARCHAR(250) NOT NULL,
	DISPLAYNAME NVARCHAR(500) NULL,
	GENDER NVARCHAR(250) NULL,
	PROFILEURL NVARCHAR(1000) NOT NULL,
	PRIMARY KEY CLUSTERED (ID, USERNAME)
);