CREATE TABLE AppUsers (
	Id INT IDENTITY(1,1) NOT NULL,
	Username NVARCHAR(250) NOT NULL,
	DisplayName NVARCHAR(500) NULL,
	Gender NVARCHAR(250) NULL,
	ProfileUrl NVARCHAR(1000) NOT NULL,
	PRIMARY KEY CLUSTERED (Id, Username)
);