CREATE DATABASE fxdb;
ALTER DATABASE fxdb CHARACTER SET utf8 COLLATE utf8_general_ci;
USE fxdb;
CREATE TABLE AppUsers (
	Id VARCHAR(36) NOT NULL,
	Username NVARCHAR(250) NOT NULL,
	DisplayName NVARCHAR(500) NULL,
	Gender NVARCHAR(250) NULL,
	ProfileUrl NVARCHAR(1000) NOT NULL,
	PRIMARY KEY CLUSTERED (Id, Username)
);